#	配置系统使用配置文件
spring:
   application:
      name: security
   profiles:
      active: dev
   http:
      encoding:
         force: true
         charset: UTF-8
         enabled: true
server:
   servlet: 
      context-path: /security
      session: 
         timeout: 86400
    
