#	配置系统使用配置文件
spring:
   application:
      name: security    #  项目名
   profiles:
      active: dev       #  指定配置文件


server:
   servlet:
      encoding:         # 配置字符编码
         enabled: true
         force: true
         charset: UTF-8
      context-path: /security    #  项目访问路径
      session: 
         timeout: 86400          #  session 有效时间
    
